"""The surfaces a claim may rest on, and the fact that they are not one list.

`I searched` is not a method. This holds the registry to the three properties
that make it worth having: every surface says what it settles AND what it does
not, every one names where to look, and the two surfaces that may never be a
basis are marked as such.
"""

from __future__ import annotations

import json

import pytest

from conftest import DATA

REGISTRY = DATA / "evidence-surfaces.json"


@pytest.fixture(scope="module")
def surfaces():
    with REGISTRY.open(encoding="utf-8") as handle:
        return json.load(handle)["surfaces"]


def test_every_surface_says_what_it_does_not_settle(surfaces):
    """A source that only says what it proves teaches a reader to over-read it."""
    for surface in surfaces:
        assert surface["settles"], surface["id"]
        assert surface["does_not_settle"], surface["id"]
        assert surface["where"], f"{surface['id']} names no place to look"


def test_the_response_outranks_the_prose(surfaces):
    """Where a reference page and a tenant's own answer disagree, the answer is
    what is true and the page is what somebody intended."""
    rank = {s["id"]: s["rank"] for s in surfaces}

    assert rank["tenant-response"] < rank["reference"]
    assert rank["reference"] < rank["roadmap"]


def test_a_portal_is_never_a_basis(surfaces):
    """THE POINT OF THE WHOLE PRODUCT. A portal settles what an administrator is
    SHOWN, which is what they believe, and not what is true. It is read as the
    second surface so a divergence can be recorded as evidence, and a rule that
    rested on it would be citing the thing being audited."""
    portal = next(s for s in surfaces if s["id"] == "admin-portal")

    assert "Never a basis for a rule" in portal["note"]
    assert "SECOND SURFACE" in portal["note"]
    assert "what is true" in portal["does_not_settle"]


def test_community_documentation_settles_nothing(surfaces):
    """It is where to look next, not what to cite.

    `settles` is asserted as an exact string on purpose. The sentence was once
    widened to admit that a good digest carries something worth having, which
    is true and is not a licence: the moment this field reads as a partial yes,
    a rule may rest on rank 5. What a digest carries belongs in the note.
    """
    community = next(s for s in surfaces if s["id"] == "community")

    assert community["settles"] == "nothing on its own"
    assert community["rank"] == max(s["rank"] for s in surfaces)


def test_a_digest_is_a_route_to_evidence_and_never_the_evidence(surfaces):
    """The one thing rank 5 can do that rank 2 cannot: reach the reader at all.

    The Tenant Admin newsletter arrives in an administrator's own centre and
    nowhere public, so a change can be real, dated, and unfindable by anyone
    outside the tenant that received it. A digest that reproduces each entry
    with its identifier hands back the address; the reading then happens at
    rank 2, against the centre or its mirror.

    What must not travel is the digest's own prose. Several of these summaries
    are generated by a model, and a paraphrase of a paraphrase is how a product
    publishes a sentence Microsoft never wrote.
    """
    community = next(s for s in surfaces if s["id"] == "community")

    assert "WHAT TO GO AND READ" in community["note"]
    assert "never travel" in community["note"]
    assert any("MC id" in place for place in community["where"]), (
        "a digest earns its place here by keeping the identifier; one that "
        "only explains has nothing this engine can check"
    )


def test_the_change_surfaces_are_present_and_distinct(surfaces):
    """Reference pages say what the product does. They do not say what it is
    about to stop doing, and a rule correct on the day it was written keeps
    being published long after it stopped being."""
    ids = {s["id"] for s in surfaces}

    assert {"message-center", "roadmap", "graph-changelog", "retirement"} <= ids

    roadmap = next(s for s in surfaces if s["id"] == "roadmap")
    assert "never a fact" in roadmap["settles"]


def test_a_rule_that_cites_a_place_cites_one_of_these(surfaces):
    """Every source URL on every shipped rule belongs to a named surface. A
    citation outside this list is a claim resting on something nobody agreed
    was evidence."""
    import yaml

    known = [place.split()[0] for surface in surfaces for place in surface["where"]]
    hosts = {place.split("/")[2] for place in known if place.startswith("http")}

    for path in sorted((DATA / "rules").rglob("*.yaml")):
        with path.open(encoding="utf-8") as handle:
            rule = yaml.safe_load(handle)

        for source in rule.get("basis", {}).get("sources", []):
            host = source["url"].split("/")[2]
            assert host in hosts, (
                f"{path.stem} cites {host}, which is not a named evidence "
                f"surface. Add the surface deliberately or cite one that exists."
            )


def test_the_two_ways_out_of_rank_five_are_not_the_same_one(surfaces):
    """A digest gives an address. An investigation gives a method.

    Both sit at the bottom of this ranking and neither may be a basis, and it
    would be easy to read that as one undifferentiated pile of things not to
    cite. It is not. A digest that keeps `MC1319213` is escalated by READING
    that message at rank 2. A first-hand investigation -- somebody ran the
    thing and wrote down what it did -- is escalated by RUNNING it here, which
    lands at rank 1 as this engine's own observation.

    The second kind decays and the first does not. A message id will read the
    same in five years; a published experiment was true against the platform on
    the day it ran, and the platform is the thing that changes. So the method
    is what travels, and the conclusion is re-established rather than quoted.
    """
    community = next(s for s in surfaces if s["id"] == "community")

    assert "TWO WAYS OUT OF RANK 5" in community["note"]
    assert "never cited for" in community["note"]
    assert any("method to run" in place for place in community["where"])


def test_the_contract_names_the_file_that_owns_the_surfaces(surfaces):
    """A decision is written once by its owner, and this is the seam.

    The surfaces were described in prose in `AGENTS.md` and listed as data
    here, which is two owners for one fact and the arrangement where a surface
    is added to one and not the other. The prose now states what the ranking is
    FOR and points at this file for what is IN it.
    """
    from pathlib import Path

    contract = (Path(__file__).resolve().parents[1] / "AGENTS.md").read_text()

    assert "data/evidence-surfaces.json" in contract, (
        "the contract must name the file that owns the surfaces, or the two "
        "drift and the prose wins by being the one people read"
    )
    assert "THE BOTTOM OF THE RANKING IS NOT ONE PILE" in contract


def test_the_contract_states_the_order_the_surfaces_are_asked_in(surfaces):
    """A list of sources is not a method, and `I searched` still is not one.

    Every named termination state must appear: a piece of work that ends in a
    sentence outside this set ends in something that reads as a fact to whoever
    reads it next.
    """
    from pathlib import Path

    contract = (Path(__file__).resolve().parents[1] / "AGENTS.md").read_text()

    assert "### The order the surfaces are asked in" in contract

    # The endings are named ONCE, in the table further down, and step 6 points
    # at it. The first draft of this restated them beside the procedure and
    # gained a seventh that belongs to a different repository's contract, which
    # is what restating a list always eventually does.
    endings = [
        line for line in contract.splitlines() if line.startswith("| `established")
        or line.startswith("| `not established") or line.startswith("| `not yet")
        or line.startswith("| `not observable") or line.startswith("| `not supported")
    ]

    assert len(endings) == 6, f"expected the six named endings, found {len(endings)}"
    assert "are not restated here" in contract
