#!/usr/bin/env python3
"""Discovery: watch the sources this product is built on, and say what moved.

Every source goes stale. Documentation lags the service, a module ships twelve
new cmdlets, a schema gains a version, and none of it announces itself to a
repository. A product whose correctness depends on somebody remembering to
re-read a page does not have correctness, it has a habit.

    tools/discovery.py            snapshot the surface, write the baseline
    tools/discovery.py --check    compare with the baseline and report

WHAT IT PRODUCES, AND THE LIST IS SHORT ON PURPOSE. Candidate changes. It does
not edit a rule, rewrite an article, or promote a `tested_with`. Correcting the
product automatically would be writing governance from a source that is not an
observation, which is the one thing the whole contract exists to prevent.

WHAT IT FAILS ON. Exactly one thing: something this product **depends on** has
disappeared. A cmdlet the collector calls, or a parameter it passes. That is
breakage and a release should stop for it. Everything new is reported and
passes, because new is a candidate and a candidate is somebody's decision.

WHY PnP FIRST. `tools/surface.py` already reads the installed module, so the
first detector needs no new dependency and nothing to scrape. The shape is the
same for every source that comes after it: snapshot, compare with a committed
baseline, ask whether anything we depend on is in the difference.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
COLLECTORS = ROOT / "src" / "m365_governance" / "data" / "collectors"
BASELINE = ROOT / "docs" / "SOURCE-BASELINE.json"

#: Governance areas, so a new cmdlet can be reported as landing somewhere this
#: product already works rather than merely existing. Same vocabulary as
#: surface.py, kept deliberately coarse: this decides what to read, not what to
#: build.
AREAS = {
    "sharing": r"Sharing|External|Anonymous|Link|Guest",
    "permissions": r"Permission|Role|EntraID|ServicePrincipal|AppRole|Access",
    "classification": r"Label|Sensitivity|Classification|Retention|Compliance",
    "tenant": r"Tenant(?!Site)",
    "sites": r"Site|Web|Hub|Template",
    "content": r"List|Item|Field|ContentType|Folder|File",
    "modernity": r"Page|Feature|CustomAction|Theme|Master",
    "apps": r"App|Spfx|Solution|AddIn",
    "agents": r"Copilot|Agent",
    "activity": r"Audit|Activity|Report|Log",
}


def pwsh(command: str) -> str | None:
    if not shutil.which("pwsh"):
        return None
    done = subprocess.run(
        ["pwsh", "-NoProfile", "-Command", command], capture_output=True, text=True
    )
    return done.stdout if done.returncode == 0 else None


def called() -> set[str]:
    """Every PnP cmdlet the collector calls, read from its own source."""
    source = "".join(
        p.read_text(encoding="utf-8")
        for p in COLLECTORS.rglob("*")
        if p.suffix in {".ps1", ".psm1"}
    )
    return set(re.findall(r"\b(?:Get|Test|Find|Measure|Connect)-PnP\w+", source))


def snapshot() -> dict | None:
    """The surface as it is right now.

    Parameters are captured only for the cmdlets this product actually calls.
    A full parameter map of 700 cmdlets would be a large file whose diff nobody
    reads; the dependency surface is the part that can break us.
    """
    version = pwsh(
        "(Get-Module -ListAvailable PnP.PowerShell | Sort-Object Version "
        "-Descending | Select-Object -First 1).Version.ToString()"
    )
    if version is None:
        return None

    names = pwsh(
        "Import-Module PnP.PowerShell -ErrorAction Stop; "
        "(Get-Command -Module PnP.PowerShell).Name"
    )
    if names is None:
        return None
    every = sorted(set(names.split()))

    ours = sorted(called() & set(every))
    parameters: dict[str, list[str]] = {}
    if ours:
        listed = "','".join(ours)
        out = pwsh(
            "Import-Module PnP.PowerShell -ErrorAction Stop; "
            f"foreach ($n in @('{listed}')) {{ "
            "$c = Get-Command $n -ErrorAction SilentlyContinue; "
            "if ($c) { $n + '=' + (($c.Parameters.Keys | Sort-Object) -join ',') } }"
        )
        for line in (out or "").splitlines():
            if "=" in line:
                name, params = line.split("=", 1)
                parameters[name.strip()] = sorted(
                    p for p in params.strip().split(",") if p
                )

    return {
        "_comment": [
            "The surface of the sources this product reads, as it was on the",
            "date below. Committed so that a later run can tell what moved.",
            "",
            "Generated by tools/discovery.py. Never edited by hand: a baseline",
            "somebody adjusted is a baseline that stops detecting.",
        ],
        "source": "PnP.PowerShell",
        "version": version.strip(),
        "cmdlet_count": len(every),
        "cmdlets": every,
        "depends_on": ours,
        "parameters_we_pass": parameters,
    }


def compare(now: dict, before: dict) -> tuple[list[str], list[str]]:
    """Breakage first, then candidates. They are not the same kind of news."""
    breaks: list[str] = []
    candidates: list[str] = []

    gone = sorted(set(before.get("depends_on", [])) - set(now["cmdlets"]))
    for name in gone:
        breaks.append(f"{name} is called by this collector and no longer exists")

    for name, params in before.get("parameters_we_pass", {}).items():
        if name not in now["parameters_we_pass"]:
            continue
        lost = sorted(set(params) - set(now["parameters_we_pass"][name]))
        if lost:
            breaks.append(f"{name} lost parameter(s) {', '.join(lost)}")

    added = sorted(set(now["cmdlets"]) - set(before.get("cmdlets", [])))
    removed = sorted(set(before.get("cmdlets", [])) - set(now["cmdlets"]))

    for name in added:
        areas = [a for a, pattern in AREAS.items() if re.search(pattern, name)]
        where = ", ".join(areas) if areas else "no area this product covers"
        candidates.append(f"new: {name} ({where})")
    for name in removed:
        candidates.append(f"gone: {name}, and nothing here called it")

    if before.get("version") != now["version"]:
        candidates.insert(
            0, f"version moved from {before.get('version')} to {now['version']}"
        )

    for name, params in now["parameters_we_pass"].items():
        old = set(before.get("parameters_we_pass", {}).get(name, []))
        if not old:
            continue
        fresh = sorted(set(params) - old)
        if fresh:
            candidates.append(f"{name} gained parameter(s) {', '.join(fresh)}")

    return breaks, candidates


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="compare with the baseline and report"
    )
    args = parser.parse_args()

    now = snapshot()
    if now is None:
        # No pwsh, or the module is absent. Saying nothing moved would be a
        # green tick over a detector that never ran.
        print("  ! PnP.PowerShell could not be read on this machine; nothing compared")
        return 0

    if not args.check:
        BASELINE.write_text(
            json.dumps(now, indent=2, sort_keys=True) + "\n", encoding="utf-8"
        )
        print(f"  wrote {BASELINE.relative_to(ROOT)}: {now['cmdlet_count']} cmdlets")
        return 0

    if not BASELINE.is_file():
        where = BASELINE.relative_to(ROOT)
        print(f"  ✗ no baseline at {where} — run tools/discovery.py")
        return 1

    before = json.loads(BASELINE.read_text(encoding="utf-8"))
    breaks, candidates = compare(now, before)

    if breaks:
        print("  ✗ something this product depends on has gone:")
        for line in breaks:
            print(f"      {line}")
        print("    A release stops here. Everything else below is a candidate.")

    if candidates:
        print(f"  ! {len(candidates)} candidate change(s) in PnP.PowerShell:")
        for line in candidates[:20]:
            print(f"      {line}")
        if len(candidates) > 20:
            print(f"      and {len(candidates) - 20} more")
        print("    Nothing was changed. Decide what is worth investigating, then")
        print("    re-run tools/discovery.py to accept the new baseline.")
    elif not breaks:
        print(f"  ✓ {now['source']} {now['version']}: nothing moved")

    return 1 if breaks else 0


if __name__ == "__main__":
    sys.exit(main())
