#!/usr/bin/env python3
"""Regenerate the examples, or check that they are current.

    python tools/examples.py            rewrite examples/
    python tools/examples.py --check    exit non-zero if any is stale

Every file in examples/ is the output of a real run against a fixture in this
repository. None of them is written by hand, and CI fails when one drifts.

That matters more than it looks. Examples in a README are read as a promise
about what the tool does, and a hand-edited one is a promise nobody is keeping:
it stays plausible while the behaviour moves underneath it. Here the promise is
executable.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EXAMPLES = ROOT / "examples"
#: The content the package ships, not a second copy at the repository root.
DATA = ROOT / "src" / "m365_governance" / "data"
FIXTURES = DATA / "fixtures" / "sharepoint"

#: One example per outcome a rule can produce, and the fixture that produces
#: it. `error` is absent because a rule cannot author it: it describes the
#: engine, and an example of it would be an example of a bug.
CASES = [
    ("pass.md", "list-within-limit", "markdown"),
    ("fail.md", "list-over-limit", "markdown"),
    ("unknown.md", "site-owners-not-collected", "markdown"),
    ("not-applicable.md", "list-unique-permissions", "markdown"),
    ("invalid-evidence.md", "list-count-invalid", "markdown"),
    # The bounded case is not an outcome, it is the reasoning: incomplete
    # evidence that still decides. It carries the JSON shape as well.
    ("bounded.md", "site-partial-expansion-decides", "markdown"),
    ("report.json", "site-partial-expansion-decides", "json"),
]


def render(fixture: str, fmt: str) -> str:
    # No `--rules`: an installed copy evaluates against the set it ships, so
    # the examples must too. Passing the repository's rules directory would
    # write "supplied by the caller: <path>" into every example — a local
    # absolute path committed to a public repository, and a rule source no
    # user would ever see. The packaged set prints "shipped with this version".
    result = subprocess.run(
        [
            sys.executable,
            "-m",
            "m365_governance.cli",
            "evaluate",
            "--evidence",
            str(FIXTURES / f"{fixture}.json"),
            "--format",
            fmt,
        ],
        capture_output=True,
        text=True,
        cwd=ROOT,
    )
    if result.returncode != 0:
        raise SystemExit(f"{fixture}: evaluate failed\n{result.stderr}")
    return result.stdout


def banner(fixture: str) -> str:
    return (
        "<!-- Generated by tools/examples.py from "
        f"fixtures/sharepoint/{fixture}.json. Do not edit by hand. -->\n\n"
    )


def build() -> dict[str, str]:
    out: dict[str, str] = {}
    for name, fixture, fmt in CASES:
        body = render(fixture, fmt)
        if fmt == "json":
            # Reformat so a diff is about the content, never about spacing.
            body = json.dumps(json.loads(body), indent=2, ensure_ascii=False) + "\n"
            out[name] = body
        else:
            out[name] = banner(fixture) + body
    return out


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; fail if anything is out of date",
    )
    args = parser.parse_args(argv)

    EXAMPLES.mkdir(exist_ok=True)
    wanted = build()

    if args.check:
        stale = []
        for name, body in wanted.items():
            path = EXAMPLES / name
            if not path.exists() or path.read_text(encoding="utf-8") != body:
                stale.append(name)
        extra = sorted(
            p.name
            for p in EXAMPLES.iterdir()
            if p.is_file() and p.name not in wanted and p.name != "README.md"
        )
        if stale or extra:
            for name in stale:
                print(f"stale:  examples/{name}", file=sys.stderr)
            for name in extra:
                print(f"orphan: examples/{name}", file=sys.stderr)
            print("\nrun: python tools/examples.py", file=sys.stderr)
            return 1
        print(f"{len(wanted)} examples up to date.")
        return 0

    for name, body in wanted.items():
        (EXAMPLES / name).write_text(body, encoding="utf-8")
    print(f"{len(wanted)} examples written.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
